### PR TITLE
Update stickers.yml

### PR DESCRIPTION
**Pull request by fredsocial**

### CODE REVIEW

**Comment by darkobits** [comment]
Hiya! 👋 

The [pack you are adding](https://signalstickers.com/pack/a06a393ecedb858aec103e15d660c6b2?key=bf078261c04ddd84f33a36190391ecfbacf0555bbfd0f32fb438493eef0e4558) contains only 1 sticker. Was this your intent?

**Comment by shu-shi** [comment]
83994b4d12b5dac8469828a09609fb9c:
  key: 6792508d9624173542d9e186a4e82b63b14f5798e71efc2f11295d59082623da
  source: Piwio Studio
  tags:
    - Line
    - Gojill
  animated: true

**Comment by shu-shi** [comment]
sorry, I do not know how to add the YAML code i just posted above into the stickers.yml code.

**Comment by darkobits** [comment]
@shu-shi That's fine. Adding it as a comment in someone else's Pull Request is probably not a good idea though, as it is likely going to get lost or ignored. Might I suggest you [open a new Issue](https://github.com/signalstickers/signalstickers/issues/new) and share your pack information there so it can be tracked properly.

**Pull request closed without merging**
