### PR TITLE
Update stickers.yml

### PR DESCRIPTION
**Pull request by jakeattack77**
Evangelion sticker pack compiled from ones i liked from various telegram eva sticker packs. listed below:
https://t.me/addstickers/neogenesisevangelion2
https://t.me/addstickers/neogenesisevangelion
https://t.me/addstickers/nge1337
https://t.me/addstickers/evangelion_LINE

I manually added tags in the file, wasnt working in the web form
link asked to include : https://signalstickers.com/pack/c208c1f160109fc1e45cb845f02f9bf1?key=8c68b816f5cb79077dc901395972ceef63b703f31cd517db151b00c43fe088e6

### CODE REVIEW

**Comment by romainricard** [comment]
Thanks! What was the problem with the tags in the form?

**Comment by jakeattack77** [comment]
> Thanks! What was the problem with the tags in the form?

it kept giving me an error, even though I had everything separated with commas, tried making them strings with ' ' but didnt work either

i added them to the file in the same format that the rest of the file was, although I see that the build is failing, not sure what happened there

**Comment by darkobits** [comment]
Something like this should be fine:

Screen Shot 2020-04-14 at 2 50 23 PM

Your YAML needs to be updated to:

```yml
c208c1f160109fc1e45cb845f02f9bf1:
  key: 8c68b816f5cb79077dc901395972ceef63b703f31cd517db151b00c43fe088e6
  source: Telegram stickers
  tags:
    - Evangelion
    - eva
    - NGE
    - anime
  nsfw: true
  original: false
```

Note there are no leading spaces on the first line, 2 leading spaces on each line following, and an additional 2 leading spaces for each item in the tags array.

**Comment by jvaubourg** [comment]
I can confirm that the form looks broken, I haven't been able to add tags either through the webpage. Even with a classic and clean comma-separated strings list like "foo, bar, baz", I always got an error telling me that I have to give a comma separated list of strings when I submit. I had to leave the field blank and add the tags by myself directly in the YML. I tried with Firefox `firefox-esr 68.7.0esr-1`  and Chromium `chromium 81.0.4044.92-1`.

@jakeattack77 You have to add a white space between the dashes and the strings, for your tags, in the YML.

**Comment by romainricard** [comment]
I can't reproduce the bug :disappointed: 
I've open issue https://github.com/signalstickers/signalstickers/issues/175, @jakeattack77 could you post your configuration there? That would help a lot! @jvaubourg if you can also provide additional info (e.g. console output if you have any), that would also be lovely!

I'll merge and close this PR for now, as I fear the tags problem will be buried in the PR flow.

**Comment by jakeattack77** [comment]
@jvaubourg @romainricard 
Thanks!, seems like it got fixed maybe? don't see the code in the stickers.yml on the main branch but I checked and I see my sticker pack on signalstickers.com. Not sure if I need to do anything to update.

**Comment by romainricard** [comment]
Yeah no worries, I updated your PR and merged it, it's now online :smiley:

**Pull request merged**
