### PR TITLE
add Celeste sticker pack

### PR DESCRIPTION
**Pull request by iomintz**
This is from the video game Celeste. It's a great game.
https://signalstickers.com/pack/c2a9a8daed732127af08e0ef20ca4c8a?key=10a049b1651d5b5109afcef7f280c1db63e7eacb4d579f0bc32dacd8b5edd188

### CODE REVIEW

**Comment by romainricard** [comment]
Thanks (again)!

**Comment by iomintz** [comment]
Why keep COVID19 pack last?

**Comment by romainricard** [comment]
As the COVID19 is striking everywhere, and we don't have a recommendation/showcased/etc feature, I manually keep it in first place. No worries, your PR was fine :smiley:

**Comment by iomintz** [comment]
ohh I see

**Pull request merged**
