### PR TITLE
Update stickers.yml

### PR DESCRIPTION
**Pull request by tenderexp**

### CODE REVIEW

**Review by Camille-cmd — CHANGES_REQUESTED** [review]
Thank you very much ! 
- Please use capitalized booleans for all the packs for `nsfw`, `original`, `animated`
- Please also add `animated` in the tags
- Please use `for children` tag instead of `for kids` as we already use this one in all other packs

**Comment by tenderexp** [comment]
Please update the YAML generator at https://signalstickers.com/contribute to conform to these guidelines.

**Comment by romainricard** [comment]
`for children` tag is one of the tag showcased on the homepage, so that's why it is more pertinent than `for kids`. We don't want to make the Contribute page more complicated, so I catch this during the review. One day, we'll probably add tag suggestions, so this will be taken care of. 

I like to add the `animated` tag to packs, so people searching for "animated" instead of `animated:true` can find animated packs. You are right, we can add this one automagically in the generator.

As for capitalized booleans, it was a mistake, sorry ; I'll fix it myself.

Thanks for contributing!

**Comment by romainricard** [comment]
A note for my future self, wondering why packs have disappeared: some packs of this PR have been merged 
- _Lovely bunny_ packs merged in https://github.com/signalstickers/signalstickers/pull/434
- _Little piggy_ packs merged in https://github.com/signalstickers/signalstickers/pull/431
- _PiggyMengmeng_ packs merged in https://github.com/signalstickers/signalstickers/pull/432 and https://github.com/signalstickers/signalstickers/pull/433

**Pull request merged**
