### PR TITLE
Added Avatar The Last Airbender sticker pack

### PR DESCRIPTION
**Pull request by bleune**
Copied from Telegram

### CODE REVIEW

**Comment by bleune** [comment]
I found one sticker with non-transparent background, I fixed the original image. Is there a way to edit the Signal sticker pack? Re-doing all the emoji's would be quite annoying..

**Comment by teynav** [comment]
> I found one sticker with non-transparent background, I fixed the original image. Is there a way to edit the Signal sticker pack? Re-doing all the emoji's would be quite annoying..

Nope there's  no way to edit it!!

**Comment by romainricard** [comment]
If you know basic Python, you can use [this lib](https://github.com/signalstickers/signalstickers-client) to do so. Else, you will have to do it by hand :disappointed: 
Thank you for noticing it!

**Comment by bleune** [comment]
Thanks, the script made things a lot easier for me. I added the fixed sticker pack.

**Comment by romainricard** [comment]
Awesome, thanks!

**Review by romainricard — APPROVED** [review]

**Pull request merged**
