### PR TITLE
feat: Improve searching.

### PR DESCRIPTION
**Pull request by darkobits**
# Improve Searching

This update overhauls the search feature, providing some new features:

* In addition to the existing fuzzy searching functionality, users may now perform targeted searches on a sticker pack's attributes using a new query grammar. Queries may consist of any number of general search terms as well as any number of attribute selectors:

  ```
  doge tag:cute tag:animal
  ```

  Users may also search on non-string attributes like `nsfw` or `original` thusly:

  ```
  original:true nsfw:false
  ```
  
  This new grammar also allows us to be more precise with our tag and author links used throughout the site, and relevant links have been updated to leverage the new search feature's query builder.

* Search queries are now persisted to the URL. This allows users to share search queries, and more broadly guarantees that (with the exception of form state) no matter where the user is on the site, the current URL will re-load it in exactly the same state.

* Updated the analytics beacon such that it will only send pings in production.

* Updated dependencies and reverted some linting error fixes from the recent ESLint migration that were false-positives.

I'll probably add a brief guide on advanced searching in the near future and link to it from the introduction on the home page or from the about page. Thoughts on this?

---

As always, consider this PR a **proposal**, and let me know if you have any feedback or concerns.

### CODE REVIEW

**Comment by romainricard** [comment]
Sorry for the late review!
My main concern is not technical but functional, on the integration of the search by tags feature. For instance, [`pug`](http://localhost:8080/?s=pug) returns good results, but [`tag:pug`](http://localhost:8080/?s=tag%3Apug) filters out relevant packs ([example](https://signalstickers.com/pack/79212537b09c13ed2de0d1dead3500e1)) that contain "pug" in their title, but not in their tag. And it seems counter-intuitive to add a tag `pug` to a pack which title already contains `pug`.

But don't get me wrong, being able to search by tag and attributes is awesome!
Other than that, I love the fact that the search query is now persisted to the URL, that will be very handy.

**Comment by darkobits** [comment]
That behavior is correct. If a user wanted to search across _all_ indexed attributes for `pug`, they would simply use `pug` as their query, and this should include the pack you linked to in the results. The query `tag:pug` would intentionally only search on the `tag` attribute.

This functionality lets us reduce noise in search results in cases where we want a targeted search. For example, after clicking on an author link and seeing a set of search results, the user's understanding is probably "ah, these must be all the packs by that author". However, with the current implementation we may be including several packs _not_ by that author because we can only search across _all_ attributes of a pack. As such, if an author has a common word in their name like `cat`, that author's link will show the user packs with `cat` in their title or tags, which is not optimal.

In the short term, I don't anticipate most user-provided queries will take advantage of these features; they are only used within the app to make our intended result sets more accurate for tag/author links. However, a search for `pug` today should produce similar results after this update -- with perhaps fewer unrelated matches at the end of the result list.

Hopefully that clarifies things a bit. If there's a specific use case that I'm not accounting for, or some part of the site that seems to not work as intended/expected with these changes, let me know and we can discuss further. 😄

**Comment by romainricard** [comment]
I forgot to write half my answer, sorry :sweat_smile: I was talking about the "search by tag" integrated in the Tags attributes in a pack's details: if an user clicks on a _tag_, I find it disturbing to search _only by tags_ (even if, yes, they clicked on a tag...)
image

I'm however totally okay with "Click on author name in pack details > search with `author:foo`". I also totally agree with you about the free search.

**Comment by darkobits** [comment]
Hmm. I suppose I have a slightly different conceptualization of tags, what an author's intent is when adding one to a pack, and what a user's expectation is when searching by them.

* I view tags as categories/groupings that an author may add their pack to by using a given tag.
* When a user clicks on/searches by a tag, they are asking to view all packs for which the author has expressed an intent to include the pack in that category.

What we currently do today is establish these categories not only by tags, but by title, and even author. This is guaranteed to produce search results that include packs where the author _never_ intended for the pack to be a member of that category.

* If an author adds the tag `cat` to their pack, that is a clear intent to include the pack in the `cat` grouping.
* If the author's name is `Catherine`, that is **not** a clear intent to include it in the `cat` grouping, but that's what the site does with the current implementation.

I think your concern is what to do with all the packs that may have `cat` in the title but _do not_ have a `cat` tag because the author never added one. These changes would drop those packs from search results, but would also drop many **false positives** as well. Attributes like title and author should not, in my opinion, implicitly include a pack in all categories mentioned/used/contained in those attributes because we can't safely infer from the presence of `cat` in a pack's title/author that the author would agree that it belongs to the category "cat". I realize this is a trade-off, but I think it brings the implementation closer to what authors and users expect.

However, If you still feel that we should include all attributes in tag searches, we can address that pretty easily by simply making the tag links on sticker pack detail pages generate a general query rather than an attribute query.

**Comment by romainricard** [comment]
I see your points. My main concern is that tags are not that often filled, let alone filled correctly. I however feel like you are right, and more importantly, coherent. I pointed out the main problem in [my previous comment](https://github.com/signalstickers/signalstickers/pull/227#issuecomment-657812626): 

> (even if, yes, they clicked on a tag...)

This is not coherent. So I agree with you, we better avoid false positives, and, if an user clicks on a tag, specify `tags:` in the search query.

Maybe we should just add an explanation to how to use the search? Like a tooltip next to the search button?

**Comment by darkobits** [comment]
> Maybe we should just add an explanation to how to use the search? Like a tooltip next to the search button?

Great idea. I've added a guide section to the About page and an icon that links to it from the search field (when focused).

**Comment by romainricard** [comment]
Love it! I just put the "link" section just bellow the "About" one, as it contains important links and was totally lost at the bottom of the page. If you are okay with it, we'll be ready to merge :tada:

<details><summary>Screenshot</summary>

image
</details>

**Pull request merged**
