### PR TITLE
improve the German version of the README document

### PR DESCRIPTION
**Pull request by 4elta**
I tried to improve the German version of the README document.

### CODE REVIEW

**Comment by 4elta** [comment]
sorry about the multiple commits ;)

**Comment by romainricard** [comment]
Thank you very much for your work! Did you make the light/dark screenshots yourself? I'll probably re-work the FR and EN versions and use them.

> sorry about the multiple commits ;)

No worries, they all will be squashed at the end!

**Comment by 4elta** [comment]
i'm happy to help.

> Did you make the light/dark screenshots yourself? 

yes, i did.

**Comment by romainricard** [comment]
Merged, thanks a lot!

**Pull request merged**
