### PR TITLE
Update stickers.yml

### PR DESCRIPTION
**Pull request by Hau-Hau**
Sugar Cubs stickers - upscaled 4 times

### CODE REVIEW

**Comment by romainricard** [comment]
All your packs (https://github.com/signalstickers/signalstickers/pull/738, https://github.com/signalstickers/signalstickers/pull/739, https://github.com/signalstickers/signalstickers/pull/740 and https://github.com/signalstickers/signalstickers/pull/741) fail to display on `signalstickers.com`. How did you make them? Does it work on your side (i.e. can you see your stickers on https://signalstickers.com/pack/655a48613c2161b1da4691573950b967?key=a485e3a035cc2b0f80cbe54918a68a5bedc1669144629e55c840d4a0f6458fc7 ? )
Thanks!

**Comment by Hau-Hau** [comment]
Hello @romainricard! No I'm also not able to see them. It's weird because every of these packs works well on Signal.

To upload them I used a bit modified script https://github.com/signalstickers/signalstickers-client/blob/master/examples/upload_stickers.py.  What I think is important is that I didn't connect images with emoji (in field of emoji I did not provide any data - I left field with empty string "").

To create these packs first i extracted stickers from web version of Facebook Messenger, then depends on stickers type I made some operations:

non-animated stickers) I upscaled every image 4x times (up to 512x512) by using waifu2x (https://github.com/nagadomi/waifu2x). I used webp format to keep lower filesize. Then I uploaded them via upload_stickers.py script.

animated stickers) I converted every image to gif format. Then I optimized every gif in terms of colors depth and overall optimization (in lossy way) to keep files small and to still have good looking animations (without any artifacts). Then I uploaded them via upload_stickers.py script.

Every package I sent I tested on Signal and they are working without any issues.
Maybe problem is related to Signal's problems with traffic?

**Comment by Hau-Hau** [comment]
I uploaded new version of my packages with added emojis. I hope it will be now working properly.

**Comment by Hau-Hau** [comment]
Bump - Ready for verification for long time same as issues below:
#738
#739
#740
#741

**Pull request closed without merging**
